version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # tsp-payout-service:
  #   build:
  #     context: .
  #     dockerfile: services/tsp-service-payout/Dockerfile
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@postgres:5432/example_db?sslmode=disable
  #   ports:
  #     - "8083:8083"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data: